
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int C = 10;
  public static final int INT = 6;
  public static final int DATE = 11;
  public static final int S = 4;
  public static final int EOF = 0;
  public static final int SEP = 2;
  public static final int ISBN = 3;
  public static final int error = 1;
  public static final int LISTBEG = 8;
  public static final int CC = 9;
  public static final int COLLOCATION = 7;
  public static final int NAME = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "ISBN",
  "S",
  "NAME",
  "INT",
  "COLLOCATION",
  "LISTBEG",
  "CC",
  "C",
  "DATE"
  };
}

