
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RO = 2;
  public static final int INT = 7;
  public static final int CM = 5;
  public static final int ATOM = 8;
  public static final int EOF = 0;
  public static final int VAR = 9;
  public static final int RC = 3;
  public static final int DOT = 4;
  public static final int error = 1;
  public static final int RUL = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RO",
  "RC",
  "DOT",
  "CM",
  "RUL",
  "INT",
  "ATOM",
  "VAR"
  };
}

