
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GEQ = 18;
  public static final int AND = 21;
  public static final int DOUBLE_TYPE = 27;
  public static final int LT = 15;
  public static final int ELSE = 31;
  public static final int EQL = 19;
  public static final int PLUS = 11;
  public static final int CO = 2;
  public static final int INT = 28;
  public static final int OR = 23;
  public static final int WHILE = 32;
  public static final int STAR = 13;
  public static final int EQG = 20;
  public static final int S = 8;
  public static final int RO = 6;
  public static final int NOT = 24;
  public static final int IF = 30;
  public static final int CC = 3;
  public static final int GT = 16;
  public static final int ID = 25;
  public static final int RC = 7;
  public static final int SO = 4;
  public static final int EOF = 0;
  public static final int C = 9;
  public static final int DIV = 14;
  public static final int MINUS = 12;
  public static final int PRINT = 33;
  public static final int error = 1;
  public static final int INT_TYPE = 26;
  public static final int EQ = 10;
  public static final int LEQ = 17;
  public static final int SC = 5;
  public static final int EQEQ = 22;
  public static final int UMINUS = 34;
  public static final int DOUBLE = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CO",
  "CC",
  "SO",
  "SC",
  "RO",
  "RC",
  "S",
  "C",
  "EQ",
  "PLUS",
  "MINUS",
  "STAR",
  "DIV",
  "LT",
  "GT",
  "LEQ",
  "GEQ",
  "EQL",
  "EQG",
  "AND",
  "EQEQ",
  "OR",
  "NOT",
  "ID",
  "INT_TYPE",
  "DOUBLE_TYPE",
  "INT",
  "DOUBLE",
  "IF",
  "ELSE",
  "WHILE",
  "PRINT",
  "UMINUS"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[18]=new String("GEQ");
		TT[21]=new String("AND");
		TT[27]=new String("DOUBLE_TYPE");
		TT[15]=new String("LT");
		TT[31]=new String("ELSE");
		TT[19]=new String("EQL");
		TT[11]=new String("PLUS");
		TT[2]=new String("CO");
		TT[28]=new String("INT");
		TT[23]=new String("OR");
		TT[32]=new String("WHILE");
		TT[13]=new String("STAR");
		TT[20]=new String("EQG");
		TT[8]=new String("S");
		TT[6]=new String("RO");
		TT[24]=new String("NOT");
		TT[30]=new String("IF");
		TT[3]=new String("CC");
		TT[16]=new String("GT");
		TT[25]=new String("ID");
		TT[7]=new String("RC");
		TT[4]=new String("SO");
		TT[0]=new String("EOF");
		TT[9]=new String("C");
		TT[14]=new String("DIV");
		TT[12]=new String("MINUS");
		TT[33]=new String("PRINT");
		TT[1]=new String("error");
		TT[26]=new String("INT_TYPE");
		TT[10]=new String("EQ");
		TT[17]=new String("LEQ");
		TT[5]=new String("SC");
		TT[22]=new String("EQEQ");
		TT[34]=new String("UMINUS");
		TT[29]=new String("DOUBLE");
	}
public String getTT(int i){return TT[i];}
}

